# Generated by Django 4.1.3 on 2023-01-25 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bio',
            name='card',
            field=models.CharField(default=0, max_length=20),
        ),
    ]
