# Generated by Django 4.1.3 on 2023-02-19 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='adress',
            field=models.CharField(default='NULLS', max_length=100),
        ),
    ]
