# Generated by Django 4.1.3 on 2023-02-19 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_history_adress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='adress',
            field=models.CharField(max_length=100),
        ),
    ]
