# Generated by Django 4.1.3 on 2023-02-24 12:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("polls", "0008_delete_customer_alter_history_datatimes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bio",
            name="balance",
            field=models.IntegerField(max_length=30),
        ),
        migrations.AlterField(
            model_name="history",
            name="datatimes",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
